import Header from '@/components/Header';
import { Montserrat } from "next/font/google";
import './globals.css';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const montserrat = Montserrat({
  subsets: ["latin"],
  display: "swap",
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" suppressHydrationWarning={true} className={montserrat.className}>
      <body>
        <Header />
        {children}
      </body>
    </html>
  )
}
